openapi: 3.2.0
info:
  title: Hubflo Project Section API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: project_section
paths:
  /api/v2/project-sections/templates/{template_id}/tasks:
    parameters:
    - name: template_id
      in: path
      required: true
      description: Project section template ID
      schema:
        type: string
    post:
      summary: Creates a task in a project section template
      deprecated: true
      security:
      - bearer_auth: []
      description: '**DEPRECATED — DO NOT USE.** Use `POST /api/v2/task_templates` instead, passing the project section id as `parent_id`. Creates a task in a project section template. When you specify a `parent_task_id` you will create a subtask. Some attributes are not available for subtasks: `clickup_id`, `monday_id`, `contact_id` and `visible_by_contact`'
      tags:
      - project_section
      parameters: []
      responses:
        '201':
          description: Task created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: ce083491-e83a-4b65-ada0-7bc4f4cdb5c8
                    name: Design mockups
                    description: Create initial mockups
                    completed: false
                    clickup_id: '123'
                    monday_id: '456'
                    kind: to_do
                    visible_by_contact: true
                    slug: ce083491-e83a-4b65-ada0-7bc4f4cdb5c8
                    created_at: '2026-07-17T13:09:44Z'
                    creator_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    creator_type: User
                    start_time: '2021-01-01T00:00:00Z'
                    end_time: '2021-01-01T01:00:00Z'
                    contact_id: null
                    project_section_id: 0ebed87a-1619-45fc-9386-c8f23d7c56c9
                    project_id: null
                    parent_task_id: null
                    workspace_id: null
                    tags: []
                    recurrence_type: null
                    recurrence_frequency: null
                    recurrence_customable_type: null
                    recurrence_week_days: null
                    recurrence_day_into_month: null
                    recurrence_days_after_completion: null
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Task name
                description:
                  type: string
                  example: Task description
                start_time:
                  type: string
                  format: date-time
                  example: '2021-01-01T00:00:00Z'
                estimated_minutes:
                  type: integer
                  example: 60
                completed:
                  type: boolean
                  example: false
                clickup_id:
                  type: string
                  example: '123'
                monday_id:
                  type: string
                  example: '123'
                kind:
                  type: string
                  enum:
                  - to_do
                  - call
                  - meeting
                  - email
                  - milestone
                  example: to_do
                visible_by_contact:
                  type: boolean
                  example: false
                parent_task_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                contact_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                user_ids:
                  type: array
                  items:
                    type: string
                  example: []
                contact_ids:
                  type: array
                  items:
                    type: string
                  example: []
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
              required:
              - name
        required: true
        description: Task attributes
      operationId: postApiV2ProjectSectionsTemplatesByTemplateIdTasks
      x-operation-id-source: derived
  /api/v2/project-sections/templates:
    get:
      summary: Retrieves the project section templates
      security:
      - bearer_auth: []
      description: Returns the project section templates
      tags:
      - project_section
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: name
        in: query
        required: false
        description: Filter by name
        schema:
          type: string
      responses:
        '200':
          description: Project section templates retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 16b01be3-8192-4d1a-90f3-634251f102db
                    name: Project Section 10
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:45Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: null
                    project_id: null
                  - id: 89ac5991-ddbf-4d1c-91f1-501ff47da9b1
                    name: Project Section 11
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:45Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: null
                    project_id: null
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectSectionsTemplates
      x-operation-id-source: derived
    post:
      summary: Creates a project section template
      security:
      - bearer_auth: []
      description: Returns the created project section template
      tags:
      - project_section
      parameters: []
      responses:
        '201':
          description: Project section template created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: f05c8be8-4202-42cb-8b90-30112abb5b87
                    name: Design Phase
                    start_date: null
                    end_date: null
                    estimated_minutes: null
                    created_at: '2026-07-17T13:09:45Z'
                    estimated_revenue_amount: 0
                    original_project_section_id: null
                    project_id: null
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Design Phase
              required:
              - name
        required: true
        description: Project section template attributes
      operationId: postApiV2ProjectSectionsTemplates
      x-operation-id-source: derived
  /api/v2/project-sections/templates/{id}:
    parameters:
    - name: id
      in: path
      required: true
      description: Project section template ID
      schema:
        type: string
    get:
      summary: Retrieves a project section template
      security:
      - bearer_auth: []
      description: Returns the project section template
      tags:
      - project_section
      responses:
        '200':
          description: Project section template retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 5ea484d3-8fe8-4ca9-acf6-298dc669e2b9
                    name: Project Section 28
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:45Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: null
                    project_id: null
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectSectionsTemplatesById
      x-operation-id-source: derived
    patch:
      summary: Updates a project section template
      security:
      - bearer_auth: []
      description: Returns the updated project section template
      tags:
      - project_section
      parameters: []
      responses:
        '200':
          description: Project section template updated
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 08812be4-f78d-4914-92f1-fe031c71c8fb
                    name: Updated Phase
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:45Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: null
                    project_id: null
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Phase
        required: true
        description: Project section template attributes
      operationId: patchApiV2ProjectSectionsTemplatesById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
