openapi: 3.2.0
info:
  title: Hubflo Chat Room API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: chat_room
paths:
  /api/v2/chat_rooms/{chat_room_id}/messages:
    get:
      summary: Retrieves messages from a given chat room
      security:
      - bearer_auth: []
      description: Returns messages
      tags:
      - chat_room
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: chat_room_id
        in: path
        required: true
        description: Chat room ID
        schema:
          type: string
      responses:
        '200':
          description: Messages retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 94038351-45ac-48a3-b01f-8608cd6645b7
                    chat_room_id: 248ca71b-0c54-479e-a672-2bc522116f08
                    body: Hello, world!
                    private: false
                    participant_id: 5b1af97d-4908-4342-b331-273b09c775c9
                    participant_type: User
                    created_at: '2026-07-17T13:08:46Z'
                    files_count: 0
                  - id: 2f93b56d-9f9c-49fc-b5c0-7c4a88c7a42a
                    chat_room_id: 248ca71b-0c54-479e-a672-2bc522116f08
                    body: Hello, world!
                    private: false
                    participant_id: 0c5f74f8-05d0-48c5-8ec6-b70ef1d07d36
                    participant_type: User
                    created_at: '2026-07-17T13:08:47Z'
                    files_count: 0
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ChatRoomsByChatRoomIdMessages
      x-operation-id-source: derived
    post:
      summary: Creates a message
      security:
      - bearer_auth: []
      description: 'Post a message within a chat room as an internal user.

        The user posting the message must be a participant in the chat room.

        Private messages are not available for announcements chat rooms.

        You can also attach files to the message.'
      tags:
      - chat_room
      parameters:
      - name: chat_room_id
        in: path
        required: true
        description: Chat room ID
        schema:
          type: string
      - name: user_id
        in: query
        required: true
        description: User ID
        schema:
          type: string
      - name: body
        in: query
        required: true
        description: Message body
        schema:
          type: string
      - name: private
        in: query
        required: false
        description: Private message
        schema:
          type: boolean
      responses:
        '201':
          description: Message created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: bf06eddf-0633-4494-89d2-2fb35ddf6d9f
                    chat_room_id: 73b4c234-198c-4db7-8ec1-6ac3fd5ca0a3
                    body: <p>Hello World! <a target="_blank" rel="noopener noreferrer nofollow" href="https://google.com"><u>google.com</u></a> and <a target="_blank" rel="noopener noreferrer nofollow" href="https://hubflo.com"><u>hubflo.com</u></a></p>
                    private: false
                    participant_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    participant_type: User
                    created_at: '2026-07-17T13:08:49Z'
                    files_count: 0
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: array
              items:
                type: string
                format: binary
        description: Files to attach
      operationId: postApiV2ChatRoomsByChatRoomIdMessages
      x-operation-id-source: derived
  /api/v2/chat_rooms/{chat_room_id}/participants:
    get:
      summary: Retrieves the participants of the given chat room
      security:
      - bearer_auth: []
      description: Returns the participants
      tags:
      - chat_room
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: chat_room_id
        in: path
        required: true
        description: Chat room ID
        schema:
          type: string
      responses:
        '200':
          description: Participants retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    participant_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    participant_type: User
                    company_name: Organization
                    email: member@organization.com
                    first_name: Memby
                    last_name: Member
                    full_name: Memby Member
                  - id: abb01058-c604-4347-9aff-5386663cf704
                    participant_id: abb01058-c604-4347-9aff-5386663cf704
                    participant_type: Contact
                    company_name: null
                    email: ramon@crist.test
                    first_name: Claretha
                    last_name: Luettgen
                    full_name: Claretha Luettgen
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ChatRoomsByChatRoomIdParticipants
      x-operation-id-source: derived
    post:
      summary: Adds a participant to the given chat room
      security:
      - bearer_auth: []
      description: Adds a participant to the chat room
      tags:
      - chat_room
      parameters:
      - name: chat_room_id
        in: path
        required: true
        description: Chat room ID
        schema:
          type: string
      - name: participant_type
        in: query
        required: true
        description: Type of participant (User or Contact)
        schema:
          type: string
      - name: participant_id
        in: query
        required: true
        description: ID of the participant to add
        schema:
          type: string
      responses:
        '201':
          description: Participant added
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    participant_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    participant_type: User
                    company_name: Organization
                    email: bot-1@hubflo.com
                    first_name: Hubflo
                    last_name: Bot
                    full_name: Hubflo API
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: postApiV2ChatRoomsByChatRoomIdParticipants
      x-operation-id-source: derived
  /api/v2/chat_rooms:
    get:
      summary: Retrieves the chat rooms
      security:
      - bearer_auth: []
      description: Returns the chat rooms
      tags:
      - chat_room
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: contact_id
        in: query
        required: false
        description: Filter by Contact ID
        schema:
          type: string
      - name: user_id
        in: query
        required: false
        description: Filter by User ID
        schema:
          type: string
      - name: name
        in: query
        required: false
        description: Filter by name
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: Filter by room type
        schema:
          type: string
      responses:
        '200':
          description: Chat room retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 2407aba0-5ec3-4b67-8a66-fed38f3be1a1
                    name: Action Required Room
                    action_required: true
                    type: regular
                    created_at: '2026-07-17T13:08:42Z'
                  - id: 047ae361-5967-4fb8-8586-3baf30d6e41e
                    name: Announcement Room
                    action_required: false
                    type: announcement
                    created_at: '2026-07-17T13:08:42Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ChatRooms
      x-operation-id-source: derived
    post:
      summary: Creates a chat room
      security:
      - bearer_auth: []
      description: Creates a chat room. Optionally links it to a workspace and adds participants.
      tags:
      - chat_room
      parameters: []
      responses:
        '201':
          description: Chat room created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 09097317-a681-4b48-94a9-ab6fb6034537
                    name: New Chat Room
                    action_required: false
                    type: regular
                    created_at: '2026-07-17T13:08:53Z'
        '400':
          description: When contact does not have authentication
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 400
                    title: Bad Request
                    message: Contact found but no associated authentication exists for this contact
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '422':
          description: 'unprocessable content: the resource can''t be created'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 422
                    title: Unprocessable Content
                    message: 'Validation failed: Title must be filled in'
              schema:
                $ref: '#/components/schemas/error_unprocessable_content'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Project Discussion
                workspace_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                user_ids:
                  type: array
                  items:
                    type: string
                  example:
                  - a0a0e818-749a-41d6-b898-43fa3ea55dd8
                contact_ids:
                  type: array
                  items:
                    type: string
                  example:
                  - a0a0e818-749a-41d6-b898-43fa3ea55dd8
              required:
              - name
        required: true
        description: Request body (flat). Chat room attributes at root.
      operationId: postApiV2ChatRooms
      x-operation-id-source: derived
  /api/v2/chat_rooms/{id}:
    parameters:
    - name: id
      in: path
      required: true
      description: Chat Room ID
      schema:
        type: string
    get:
      summary: Retrieves a chat room
      security:
      - bearer_auth: []
      description: Returns the chat room
      tags:
      - chat_room
      responses:
        '200':
          description: Chat Room retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 730b3e0e-fa2c-4f1d-958b-99544e01a2ed
                    name: My Chat Room
                    action_required: false
                    type: regular
                    created_at: '2026-07-17T13:08:54Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ChatRoomsById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unprocessable_content:
      description: A response describing a validation error
      type: object
      properties:
        status:
          type: integer
          example: 422
        title:
          type: string
          example: Unprocessable Content
        message:
          type: string
          example: 'Validation failed: Title can''t be blank'
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
