openapi: 3.2.0
info:
  title: Hubflo Project API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: Project
paths:
  /api/v2/projects/{project_id}/contacts:
    get:
      summary: Retrieves the contacts of a project
      security:
      - bearer_auth: []
      description: Returns the contacts of a project. Only the first 100 tags of each contact are returned
      tags:
      - Project
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: project_id
        in: path
        required: true
        description: Project ID
        schema:
          type: string
      responses:
        '200':
          description: Contacts retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: d86f87ce-5189-4d98-9597-4224fcf47b88
                    first_name: Vince
                    last_name: Thompson
                    full_name: Vince Thompson
                    email: hello-263@hubflo.com
                    contact_type: prospect
                    priority: high
                    phone: '       263'
                    secondary_phone: null
                    address: 263 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    job_title: null
                    url_linkedin: https://www.linkedin.com/in/vince-thompson
                    hubspot_id: null
                    created_at: '2026-07-17T13:09:46Z'
                    company_name: null
                    company_id: null
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    tags: []
                  - id: 6b04b3a4-4018-4743-8033-d995d35acd67
                    first_name: Clifton
                    last_name: Kautzer
                    full_name: Clifton Kautzer
                    email: hello-262@hubflo.com
                    contact_type: prospect
                    priority: medium
                    phone: '       262'
                    secondary_phone: null
                    address: 262 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    job_title: null
                    url_linkedin: https://www.linkedin.com/in/clifton-kautzer
                    hubspot_id: null
                    created_at: '2026-07-17T13:09:46Z'
                    company_name: null
                    company_id: null
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectsByProjectIdContacts
      x-operation-id-source: derived
  /api/v2/projects/{project_id}/sections:
    get:
      summary: Retrieves the sections of a project
      security:
      - bearer_auth: []
      description: Returns the sections of a project
      tags:
      - Project
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: project_id
        in: path
        required: true
        description: Project ID
        schema:
          type: string
      - name: name
        in: query
        required: false
        description: Filter by section name
        schema:
          type: string
      responses:
        '200':
          description: Sections retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 17d10cb1-d90d-4522-acf3-f0ceb9bbd4ea
                    name: No section
                    start_date: null
                    end_date: null
                    estimated_minutes: null
                    created_at: '2026-07-17T13:09:46Z'
                    estimated_revenue_amount: 0
                    original_project_section_id: null
                    project_id: 12a54ee0-441c-483c-9528-3f25485fc993
                  - id: 218c8eb2-c667-47cc-ba4a-1e2a77c21814
                    name: Project Section 38
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:46Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: null
                    project_id: 12a54ee0-441c-483c-9528-3f25485fc993
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectsByProjectIdSections
      x-operation-id-source: derived
    post:
      summary: Creates a section
      security:
      - bearer_auth: []
      description: Creates a section from a template
      tags:
      - Project
      parameters:
      - name: project_id
        in: path
        required: true
        description: Project ID
        schema:
          type: string
      responses:
        '201':
          description: when project is assigned to workspace
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: cad92ff0-0332-43f0-b2a8-3726cd05b419
                    name: Project Section 60
                    start_date: '2026-07-16'
                    end_date: '2026-07-18'
                    estimated_minutes: 222
                    created_at: '2026-07-17T13:09:47Z'
                    estimated_revenue_amount: 100000
                    original_project_section_id: da06aad6-7a6f-4c20-9458-ee2fea4f1195
                    project_id: 14826476-5c60-484b-bbe7-a921abcdf4af
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                original_project_section_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                link_to_project_workspace:
                  type: boolean
                  example: true
              required:
              - original_project_section_id
        required: true
        description: Section attributes
      operationId: postApiV2ProjectsByProjectIdSections
      x-operation-id-source: derived
  /api/v2/projects/{project_id}/users:
    get:
      summary: Retrieves the users of a project
      security:
      - bearer_auth: []
      description: Returns the users of a project.
      tags:
      - Project
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: project_id
        in: path
        required: true
        description: Project ID
        schema:
          type: string
      responses:
        '200':
          description: Users retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 57f32ea0-060d-4202-a48a-71011ada479c
                    first_name: Jamison
                    last_name: Schowalter
                    email: hello-94@hubflo.com
                    phone: null
                    created_at: '2026-07-17T13:09:47Z'
                  - id: 53d7ca41-1319-4695-917d-76c216dc99ec
                    first_name: Melvin
                    last_name: DAmore
                    email: hello-95@hubflo.com
                    phone: null
                    created_at: '2026-07-17T13:09:47Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectsByProjectIdUsers
      x-operation-id-source: derived
  /api/v2/projects:
    get:
      summary: Retrieves the projects
      security:
      - bearer_auth: []
      description: Retrieves the projects. Only the first 100 tags of each project are returned
      tags:
      - Project
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: owner_id
        in: query
        required: false
        description: Filter by owner ID
        schema:
          type: string
      - name: owner_email
        in: query
        required: false
        description: Filter by owner email
        schema:
          type: string
      - name: contact_id
        in: query
        required: false
        description: Filter by contact ID
        schema:
          type: string
      - name: contact_email
        in: query
        required: false
        description: Filter by contact email
        schema:
          type: string
      - name: contact_phone
        in: query
        required: false
        description: Filter by contact phone
        schema:
          type: string
      - name: workspace_id
        in: query
        required: false
        description: Filter by workspace ID
        schema:
          type: string
      - name: name
        in: query
        required: false
        description: Filter by name
        schema:
          type: string
      responses:
        '200':
          description: Projects retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 5b34d93f-89a0-415b-8e15-90613275c2a7
                    name: Project 88
                    start_date: '2022-01-01'
                    end_date: '2022-12-19'
                    created_at: '2026-07-17T13:09:48Z'
                    estimated_revenue_amount: 10000
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    stage_id: b4d9a0d6-68ee-4f33-86c7-eb8a40d27322
                    stage_name: Project Stage 106
                    workspace_id: null
                    primary_contact_id: null
                    primary_contact_full_name: null
                    address: 88 RUE DE PONTHIEU
                    latitude: 48.8763
                    longitude: 2.3183
                    state: Paris
                    city: Paris
                    postal_code: '75008'
                    country: null
                    tags: []
                  - id: ad06e1e5-ea11-41b5-87ce-ad6c6368911f
                    name: Project 87
                    start_date: '2022-01-01'
                    end_date: '2022-12-19'
                    created_at: '2026-07-17T13:09:48Z'
                    estimated_revenue_amount: 10000
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    stage_id: 5f6ba549-26d8-44c3-9674-ca5f562b3ed1
                    stage_name: Project Stage 105
                    workspace_id: null
                    primary_contact_id: null
                    primary_contact_full_name: null
                    address: 87 RUE DE PONTHIEU
                    latitude: 48.8763
                    longitude: 2.3183
                    state: Paris
                    city: Paris
                    postal_code: '75008'
                    country: null
                    tags: []
      operationId: getApiV2Projects
      x-operation-id-source: derived
    post:
      summary: Creates a project
      security:
      - bearer_auth: []
      description: 'Creates a project. Only 100 tags maximum can be specified. To fill in a custom field, add the custom field ''serialization_name'' to the request

        params, with the desired value.'
      tags:
      - Project
      parameters: []
      responses:
        '201':
          description: Project created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 84548975-bfea-423d-973b-fa0656c06aff
                    name: Project name
                    start_date: '2025-01-01'
                    end_date: '2025-01-31'
                    created_at: '2026-07-17T13:09:49Z'
                    estimated_revenue_amount: 1000
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    stage_id: 6986e380-b97a-43d4-ab8e-cce50a69580b
                    stage_name: 📥 New
                    workspace_id: null
                    primary_contact_id: null
                    primary_contact_full_name: null
                    address: null
                    latitude: null
                    longitude: null
                    state: null
                    city: null
                    postal_code: null
                    country: null
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Project name
                estimated_revenue_amount:
                  type: number
                  example: 1000
                start_date:
                  type: string
                  example: '2025-01-01'
                end_date:
                  type: string
                  example: '2025-01-31'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                owner_email:
                  type: string
                  example: john.doe@example.com
                stage_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                primary_contact_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                address:
                  type: string
                  example: 55 rue Faubourg Saint-Honoré, 75008 Paris
                workspace_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
                user_ids:
                  type: array
                  items:
                    type: string
                  example:
                  - a0a0e818-749a-41d6-b898-43fa3ea55dd8
              required:
              - name
        required: true
        description: Project attributes
      operationId: postApiV2Projects
      x-operation-id-source: derived
  /api/v2/projects/{id}:
    parameters:
    - name: id
      in: path
      required: true
      description: Project ID
      schema:
        type: string
    get:
      summary: Retrieves a project
      security:
      - bearer_auth: []
      description: Returns the project. . Only the first 100 tags of the project are returned
      tags:
      - Project
      responses:
        '200':
          description: Project retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: a7bc02a3-25dc-46ac-9687-c4fd9aaa2e00
                    name: Project 111
                    start_date: '2022-01-01'
                    end_date: '2022-12-19'
                    created_at: '2026-07-17T13:09:49Z'
                    estimated_revenue_amount: 10000
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    stage_id: 0ab87ec0-fc99-4c90-b86d-77141ba68488
                    stage_name: Project Stage 145
                    workspace_id: null
                    primary_contact_id: null
                    primary_contact_full_name: null
                    address: 112 RUE DE PONTHIEU
                    latitude: 48.8763
                    longitude: 2.3183
                    state: Paris
                    city: Paris
                    postal_code: '75008'
                    country: null
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ProjectsById
      x-operation-id-source: derived
    patch:
      summary: Updates a project
      security:
      - bearer_auth: []
      description: Updates a project. Only 100 tags maximum can be specified. If the tags key is present, the tags provided in the request will replace the existing tags. To fill in a custom field, add the custom field 'serialization_name' to the request params, with the desired value.
      tags:
      - Project
      parameters: []
      responses:
        '200':
          description: Project updated
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 00e498e4-b68b-4ab6-b9b0-6b0183287d9b
                    name: Project name
                    start_date: '2025-01-01'
                    end_date: '2025-01-31'
                    created_at: '2026-07-17T13:09:50Z'
                    estimated_revenue_amount: 1000
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    stage_id: 1daabf58-f01e-4de5-a41b-905fdd0c2b89
                    stage_name: Project Stage 150
                    workspace_id: null
                    primary_contact_id: null
                    primary_contact_full_name: null
                    address: 117 RUE DE PONTHIEU
                    latitude: 48.8763
                    longitude: 2.3183
                    state: Paris
                    city: Paris
                    postal_code: '75008'
                    country: null
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '422':
          description: 'unprocessable content: the resource can''t be created'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 422
                    title: Unprocessable Content
                    message: 'Validation failed: Title must be filled in'
              schema:
                $ref: '#/components/schemas/error_unprocessable_content'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Project name
                estimated_revenue_amount:
                  type: number
                  example: 1000
                start_date:
                  type: string
                  example: '2025-01-01'
                end_date:
                  type: string
                  example: '2025-01-31'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                owner_email:
                  type: string
                  example: john.doe@example.com
                stage_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                primary_contact_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                address:
                  type: string
                  example: 55 rue Faubourg Saint-Honoré, 75008 Paris
                workspace_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
                user_ids:
                  type: array
                  items:
                    type: string
                  example:
                  - a0a0e818-749a-41d6-b898-43fa3ea55dd8
              required:
              - name
        required: true
        description: Project attributes
      operationId: patchApiV2ProjectsById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unprocessable_content:
      description: A response describing a validation error
      type: object
      properties:
        status:
          type: integer
          example: 422
        title:
          type: string
          example: Unprocessable Content
        message:
          type: string
          example: 'Validation failed: Title can''t be blank'
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
