openapi: 3.2.0
info:
  title: Hubflo Contact API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: Contact
paths:
  /api/v2/contacts/{contact_id}/workspaces:
    get:
      summary: Retrieves the workspaces of the given contact.
      security:
      - bearer_auth: []
      description: Returns the workspaces
      tags:
      - Contact
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: contact_id
        in: path
        required: true
        description: Contact ID
        schema:
          type: string
      responses:
        '200':
          description: Workspaces retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 09c6e3f6-5d58-4edb-a754-b13fb7e4156e
                    title: Title 4
                    subtitle: MyString
                    welcome_message: null
                    archived: false
                    template: false
                    created_at: '2026-07-17T13:08:59Z'
                    project_id: null
                    chat_room_id: null
                    tags: []
                  - id: da52f0c4-f26b-41dc-ae6c-510abc4775bb
                    title: Title 3
                    subtitle: MyString
                    welcome_message: null
                    archived: false
                    template: false
                    created_at: '2026-07-17T13:08:58Z'
                    project_id: null
                    chat_room_id: null
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ContactsByContactIdWorkspaces
      x-operation-id-source: derived
  /api/v2/contacts/{contact_id}/workspaces/{id}:
    get:
      summary: Retrieves a workspace of the given contact.
      security:
      - bearer_auth: []
      description: Returns the workspace
      tags:
      - Contact
      parameters:
      - name: contact_id
        in: path
        required: true
        description: Contact ID
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: Workspace ID
        schema:
          type: string
      responses:
        '200':
          description: Workspace retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: c64f2b17-6b17-4633-a1d3-8653edddb340
                    title: Title 20
                    subtitle: MyString
                    welcome_message: null
                    archived: false
                    template: false
                    created_at: '2026-07-17T13:09:00Z'
                    project_id: null
                    chat_room_id: null
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ContactsByContactIdWorkspacesById
      x-operation-id-source: derived
  /api/v2/contacts:
    get:
      summary: Retrieves the contacts
      security:
      - bearer_auth: []
      description: Returns the contacts. Only the first 100 tags of each contact are returned
      tags:
      - Contact
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: owner_id
        in: query
        required: false
        description: Filter by owner ID
        schema:
          type: string
      - name: phone
        in: query
        required: false
        description: Filter by phone number
        schema:
          type: string
      - name: email
        in: query
        required: false
        description: Filter by email
        schema:
          type: string
      - name: project_id
        in: query
        required: false
        description: Filter by project ID
        schema:
          type: string
      - name: company_id
        in: query
        required: false
        description: Filter by company ID
        schema:
          type: string
      - name: contact_id
        in: query
        required: false
        description: Filter by contact ID
        schema:
          type: string
      - name: linkedin
        in: query
        required: false
        description: Filter by LinkedIn
        schema:
          type: string
      responses:
        '200':
          description: Contacts retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 192836e1-e735-4bd8-b481-f7347b12304e
                    first_name: Rosario
                    last_name: Cartwright
                    full_name: Rosario Cartwright
                    email: hello-43@hubflo.com
                    contact_type: prospect
                    priority: low
                    phone: '1234567890'
                    secondary_phone: null
                    address: 43 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    job_title: null
                    url_linkedin: https://linkedin.com/in/foobar
                    hubspot_id: null
                    created_at: '2026-07-17T13:09:01Z'
                    company_name: Company 46
                    company_id: 3014557c-6596-4bb3-a68c-a3491f54ef10
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
                  - id: e9b18364-1924-46ec-af15-42145277180e
                    first_name: Coral
                    last_name: Morar
                    full_name: Coral Morar
                    email: hello-42@hubflo.com
                    contact_type: prospect
                    priority: medium
                    phone: '        42'
                    secondary_phone: null
                    address: 42 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    job_title: null
                    url_linkedin: https://www.linkedin.com/in/coral-morar
                    hubspot_id: null
                    created_at: '2026-07-17T13:09:01Z'
                    company_name: null
                    company_id: null
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2Contacts
      x-operation-id-source: derived
    post:
      summary: Creates a contact
      security:
      - bearer_auth: []
      description: 'Creates a contact. Only 100 tags maximum can be specified.

        To fill in a custom field, add the custom field ''serialization_name'' to the request

        params, with the desired value.'
      tags:
      - Contact
      parameters: []
      responses:
        '201':
          description: Contact created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 4536bad3-b60f-4599-a863-eb3a64c51d15
                    first_name: John
                    last_name: Doe
                    full_name: John Doe
                    email: john.doe@example.com
                    contact_type: prospect
                    priority: low
                    phone: '1234567890'
                    secondary_phone: 0987654321
                    address: 123 Main St
                    postal_code: '12345'
                    city: Anytown
                    state: NY
                    country: USA
                    job_title: CEO
                    url_linkedin: https://linkedin.com/in/johndoe
                    hubspot_id: '123456'
                    created_at: '2026-07-17T13:09:04Z'
                    company_name: null
                    company_id: null
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                full_name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                phone:
                  type: string
                  example: '1234567890'
                secondary_phone:
                  type: string
                  example: 0987654321
                contact_type:
                  type: string
                  enum:
                  - prospect
                  - client
                  - partner
                  - provider
                  example: prospect
                priority:
                  type: string
                  enum:
                  - low
                  - medium
                  - high
                  example: low
                address:
                  type: string
                  example: 123 Main St
                postal_code:
                  type: string
                  example: '12345'
                city:
                  type: string
                  example: Anytown
                state:
                  type: string
                  example: NY
                country:
                  type: string
                  example: USA
                job_title:
                  type: string
                  example: CEO
                url_linkedin:
                  type: string
                  format: uri
                  example: https://linkedin.com/in/johndoe
                hubspot_id:
                  type: string
                  example: '123456'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                owner_email:
                  type: string
                  format: email
                  example: the.owner@company.com
                company_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                company_name:
                  type: string
                  example: Company Inc.
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
              required:
              - first_name
              - last_name
        required: true
        description: Contact attributes
      operationId: postApiV2Contacts
      x-operation-id-source: derived
  /api/v2/contacts/{id}:
    parameters:
    - name: id
      in: path
      required: true
      description: Contact ID
      schema:
        type: string
    get:
      summary: Retrieves a contact
      security:
      - bearer_auth: []
      description: Returns the contact. Only the first 100 tags of the contact are returned
      tags:
      - Contact
      responses:
        '200':
          description: Contact retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 5c5f7f4b-a58b-4fd7-b630-b33d2bec2db2
                    first_name: Lida
                    last_name: Conn
                    full_name: Lida Conn
                    email: hello-90@hubflo.com
                    contact_type: prospect
                    priority: low
                    phone: '        90'
                    secondary_phone: null
                    address: 90 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    job_title: null
                    url_linkedin: https://www.linkedin.com/in/lida-conn
                    hubspot_id: null
                    created_at: '2026-07-17T13:09:05Z'
                    company_name: null
                    company_id: null
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2ContactsById
      x-operation-id-source: derived
    patch:
      summary: Updates a contact
      security:
      - bearer_auth: []
      description: Updates a contact. Only 100 tags maximum can be specified. If the tags key is present, the tags provided in the request will replace the existing tags. To fill in a custom field, add the custom field 'serialization_name' to the request params, with the desired value.
      tags:
      - Contact
      parameters: []
      responses:
        '200':
          description: Contact updated
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 9c897537-677d-4b0a-9abd-f737a674a958
                    first_name: John
                    last_name: Doe
                    full_name: John Doe
                    email: john.doe@example.com
                    contact_type: prospect
                    priority: low
                    phone: '1234567890'
                    secondary_phone: 0987654321
                    address: 123 Main St
                    postal_code: '12345'
                    city: Anytown
                    state: NY
                    country: USA
                    job_title: CEO
                    url_linkedin: https://linkedin.com/in/johndoe
                    hubspot_id: '123456'
                    created_at: '2026-07-17T13:09:05Z'
                    company_name: null
                    company_id: null
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '422':
          description: 'unprocessable content: the resource can''t be created'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 422
                    title: Unprocessable Content
                    message: 'Validation failed: Full name must be filled in'
              schema:
                $ref: '#/components/schemas/error_unprocessable_content'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                full_name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                phone:
                  type: string
                  example: '1234567890'
                secondary_phone:
                  type: string
                  example: 0987654321
                contact_type:
                  type: string
                  enum:
                  - prospect
                  - client
                  - partner
                  - provider
                  example: prospect
                priority:
                  type: string
                  enum:
                  - low
                  - medium
                  - high
                  example: low
                address:
                  type: string
                  example: 123 Main St
                postal_code:
                  type: string
                  example: '12345'
                city:
                  type: string
                  example: Anytown
                state:
                  type: string
                  example: NY
                country:
                  type: string
                  example: USA
                job_title:
                  type: string
                  example: CEO
                url_linkedin:
                  type: string
                  format: uri
                  example: https://linkedin.com/in/johndoe
                hubspot_id:
                  type: string
                  example: '123456'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                owner_email:
                  type: string
                  format: email
                  example: the.owner@company.com
                company_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                company_name:
                  type: string
                  example: Company Inc.
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
              required:
              - first_name
              - last_name
        required: true
        description: Contact attributes
      operationId: patchApiV2ContactsById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unprocessable_content:
      description: A response describing a validation error
      type: object
      properties:
        status:
          type: integer
          example: 422
        title:
          type: string
          example: Unprocessable Content
        message:
          type: string
          example: 'Validation failed: Title can''t be blank'
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
