openapi: 3.2.0
info:
  title: Hubflo Company API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: Company
paths:
  /api/v2/companies:
    get:
      summary: Retrieves the companies
      security:
      - bearer_auth: []
      description: Returns the companies. Only the first 100 tags of each company are returned.
      tags:
      - Company
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: project_id
        in: query
        required: false
        description: Filter by project ID
        schema:
          type: string
      - name: parent_id
        in: query
        required: false
        description: Filter by parent ID
        schema:
          type: string
      - name: owner_id
        in: query
        required: false
        description: Filter by owner ID
        schema:
          type: string
      - name: contact_id
        in: query
        required: false
        description: Filter by contact ID
        schema:
          type: string
      - name: name
        in: query
        required: false
        description: Filter by name
        schema:
          type: string
      responses:
        '200':
          description: Companies retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 0448a66b-1f87-4bb2-ba1c-8bd2e1e83dca
                    name: Company 3
                    business_description: null
                    email: null
                    address: 3 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    staff: null
                    siret: '003'
                    vat_number: FR003
                    website: null
                    url_linkedin: null
                    hubspot_id: null
                    parent_id: null
                    created_at: '2026-07-17T13:08:54Z'
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
                  - id: 59d569e1-fdf4-4ca6-9ea0-a968d0152b33
                    name: Company 2
                    business_description: null
                    email: null
                    address: 2 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    staff: null
                    siret: '002'
                    vat_number: FR002
                    website: null
                    url_linkedin: null
                    hubspot_id: null
                    parent_id: null
                    created_at: '2026-07-17T13:08:54Z'
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2Companies
      x-operation-id-source: derived
    post:
      summary: Creates a company
      security:
      - bearer_auth: []
      description: 'Creates a company. Only 100 tags maximum can be specified.

        To fill in a custom field, add the custom field ''serialization_name'' to the request

        params, with the desired value.'
      tags:
      - Company
      parameters: []
      responses:
        '201':
          description: Company created
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 80cb8f41-6b48-4448-84a7-b08b64a7bbab
                    name: MIB
                    business_description: Monitors and polices aliens
                    email: frank@mib.com
                    address: 504 Battery Drive
                    postal_code: '10004'
                    city: NYC
                    state: NY
                    country: USA
                    staff: '100'
                    siret: null
                    vat_number: '123456789'
                    website: https://mib.com
                    url_linkedin: https://linkedin.com/in/frank
                    hubspot_id: '123456'
                    parent_id: null
                    created_at: '2026-07-17T13:08:57Z'
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Company Inc.
                business_description:
                  type: string
                  example: A company
                email:
                  type: string
                  format: email
                  example: company@example.com
                address:
                  type: string
                  example: 123 Main St
                postal_code:
                  type: string
                  example: '12345'
                city:
                  type: string
                  example: Anytown
                state:
                  type: string
                  example: NY
                country:
                  type: string
                  example: USA
                staff:
                  type: string
                  example: '12'
                siret:
                  type: string
                  example: '123456789'
                vat_number:
                  type: string
                  example: '123456789'
                website:
                  type: string
                  format: uri
                  example: https://company.com
                url_linkedin:
                  type: string
                  format: uri
                  example: https://linkedin.com/in/johndoe
                hubspot_id:
                  type: string
                  example: '123456'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
              required:
              - name
        required: true
        description: Company attributes
      operationId: postApiV2Companies
      x-operation-id-source: derived
  /api/v2/companies/{id}:
    parameters:
    - name: id
      in: path
      required: true
      description: Company ID
      schema:
        type: string
    get:
      summary: Retrieves a company
      security:
      - bearer_auth: []
      description: Returns the company. Only the first 100 tags of the company are returned.
      tags:
      - Company
      responses:
        '200':
          description: Company retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: bd0ab49b-5070-4be6-b960-55a2e4311786
                    name: Company 32
                    business_description: null
                    email: null
                    address: 32 RUE DE PONTHIEU
                    postal_code: '75008'
                    city: Paris
                    state: Paris
                    country: null
                    staff: null
                    siret: '032'
                    vat_number: FR032
                    website: null
                    url_linkedin: null
                    hubspot_id: null
                    parent_id: null
                    created_at: '2026-07-17T13:08:57Z'
                    owner_id: 780e98ee-8ca2-49fa-bd4d-6d2a644ee40a
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2CompaniesById
      x-operation-id-source: derived
    patch:
      summary: Updates a company
      security:
      - bearer_auth: []
      description: Updates a company. Only 100 tags maximum can be specified. If the tags key is present, the tags provided in the request will replace the existing tags. To fill in a custom field, add the custom field 'serialization_name' to the request params, with the desired value.
      tags:
      - Company
      parameters: []
      responses:
        '200':
          description: Company updated
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 2dd2c8c3-74b1-4efa-aed7-60ac7327d13a
                    name: MIB
                    business_description: Monitors and polices aliens
                    email: frank@mib.com
                    address: 504 Battery Drive
                    postal_code: '10004'
                    city: NYC
                    state: NY
                    country: USA
                    staff: '100'
                    siret: '037'
                    vat_number: '123456789'
                    website: https://mib.com
                    url_linkedin: https://linkedin.com/in/frank
                    hubspot_id: '123456'
                    parent_id: null
                    created_at: '2026-07-17T13:08:58Z'
                    owner_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    tags: []
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '422':
          description: 'unprocessable content: the resource can''t be created'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 422
                    title: Unprocessable Content
                    message: 'Validation failed: Name must be filled in'
              schema:
                $ref: '#/components/schemas/error_unprocessable_content'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Company Inc.
                business_description:
                  type: string
                  example: A company
                email:
                  type: string
                  format: email
                  example: company@example.com
                address:
                  type: string
                  example: 123 Main St
                postal_code:
                  type: string
                  example: '12345'
                city:
                  type: string
                  example: Anytown
                state:
                  type: string
                  example: NY
                country:
                  type: string
                  example: USA
                staff:
                  type: string
                  example: '12'
                siret:
                  type: string
                  example: '123456789'
                vat_number:
                  type: string
                  example: '123456789'
                website:
                  type: string
                  format: uri
                  example: https://company.com
                url_linkedin:
                  type: string
                  format: uri
                  example: https://linkedin.com/in/johndoe
                hubspot_id:
                  type: string
                  example: '123456'
                owner_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
                tags:
                  type: array
                  items:
                    type: string
                  example:
                  - tag1
                  - tag2
              required:
              - name
        required: true
        description: Company attributes
      operationId: patchApiV2CompaniesById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unprocessable_content:
      description: A response describing a validation error
      type: object
      properties:
        status:
          type: integer
          example: 422
        title:
          type: string
          example: Unprocessable Content
        message:
          type: string
          example: 'Validation failed: Title can''t be blank'
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
