openapi: 3.2.0
info:
  title: Hubflo Comment API
  version: v2
  description: The Hubflo API allows you to write and read data from the Hubflo application.
servers:
- url: https://app.hubflo.com
  description: The production API server
- url: https://staging.hubflo.com
  description: The staging API server
- url: http://localhost:3000
  description: The local API server
tags:
- name: Comment
paths:
  /api/v2/tasks/{task_id}/comments:
    post:
      summary: Creates a comment
      security:
      - bearer_auth: []
      description: 'Add a comment to a task.

        Specify the author of the comment with the author_id parameter.'
      tags:
      - Comment
      parameters:
      - name: task_id
        in: path
        required: true
        description: Task ID
        schema:
          type: string
      responses:
        '201':
          description: Comment created on subtask
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    body: Body content
                    id: a7d12379-1e6e-48db-afbd-034044931fac
                    author_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    author_type: User
                    task_id: 86abdcb0-e151-4f09-a622-336d1ed97bc7
                    created_at: '2026-07-17T13:10:00Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '422':
          description: 'unprocessable content: the resource can''t be created'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 422
                    title: Unprocessable Content
                    message: Record invalid
              schema:
                $ref: '#/components/schemas/error_unprocessable_content'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: Super feature!
                author_id:
                  type: string
                  example: a0a0e818-749a-41d6-b898-43fa3ea55dd8
              required:
              - body
              - author_id
        required: true
        description: Comment attributes
      operationId: postApiV2TasksByTaskIdComments
      x-operation-id-source: derived
    get:
      summary: Retrieves task comments
      security:
      - bearer_auth: []
      description: Returns all comments associated with a task, sorted by creation date in descending order
      tags:
      - Comment
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        required: false
        description: Number of items per page (max 100)
        example: 10
        schema:
          type: number
      - name: task_id
        in: path
        required: true
        description: Task ID
        schema:
          type: string
      responses:
        '200':
          description: Comments retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
            X-Page:
              schema:
                type: integer
              description: Current page number
            X-Per-Page:
              schema:
                type: integer
              description: Number of items per page
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages
            X-Next-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Next page number
            X-Prev-Page:
              schema:
                type:
                - integer
                - 'null'
              description: Previous page number
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items
          content:
            application/json:
              examples:
                example:
                  value:
                  - body: Comment body
                    id: c6e5ce7d-3f46-42d8-a0cb-1efd9aa6b6d2
                    author_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    author_type: User
                    task_id: f427b7c2-bbf9-4036-8f61-5bcd7a9b9316
                    created_at: '2026-07-17T13:10:00Z'
                  - body: Comment body
                    id: 3b8cb145-7e66-44aa-a7bd-98c72b4ad0a9
                    author_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    author_type: User
                    task_id: f427b7c2-bbf9-4036-8f61-5bcd7a9b9316
                    created_at: '2026-07-17T13:10:00Z'
                  - body: Comment body
                    id: 10495c29-d075-439c-b4c5-9bd45673fe02
                    author_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    author_type: User
                    task_id: f427b7c2-bbf9-4036-8f61-5bcd7a9b9316
                    created_at: '2026-07-17T13:10:00Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2TasksByTaskIdComments
      x-operation-id-source: derived
  /api/v2/tasks/{task_id}/comments/{id}:
    get:
      summary: Retrieves a comment
      security:
      - bearer_auth: []
      description: Returns a specific comment of a task
      tags:
      - Comment
      parameters:
      - name: task_id
        in: path
        required: true
        description: Task ID
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: Comment ID
        schema:
          type: string
      responses:
        '200':
          description: Comment retrieved
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            X-Organization-ID:
              schema:
                type: string
              description: The organization ID
            X-Rate-Limit:
              schema:
                type: integer
              description: Max allowed requests in the current period
            X-Remaining-Requests:
              schema:
                type: integer
              description: Remaining requests in the current period
          content:
            application/json:
              examples:
                example:
                  value:
                    body: Comment body
                    id: 2e7d06f7-49b0-4d69-be08-315ae09972f9
                    author_id: e68a6422-fdb4-4c64-922a-8ac109b3ed33
                    author_type: User
                    task_id: 81bf0e8f-fb03-4395-b11e-7f9f5963bb4b
                    created_at: '2026-07-17T13:10:01Z'
        '401':
          description: 'unauthorized: the Authorization header is missing or invalid'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 401
                    title: Unauthorized
                    message: Invalid API token
              schema:
                $ref: '#/components/schemas/error_unauthorized'
        '404':
          description: 'not found: the resource is not found'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    title: Not Found
                    message: Resource not found
              schema:
                $ref: '#/components/schemas/error_not_found'
        '429':
          description: 'too many requests: the user has reached the rate limit'
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 429
                    title: Too Many Requests
                    message: Rate limit reached. Please wait for a couple of minutes.
              schema:
                $ref: '#/components/schemas/error_too_many_requests'
      operationId: getApiV2TasksByTaskIdCommentsById
      x-operation-id-source: derived
components:
  schemas:
    error_not_found:
      description: A response describing a not found error
      type: object
      properties:
        status:
          type: integer
          example: 404
        title:
          type: string
          example: Not Found
        message:
          type: string
          example: Resource not found
      required:
      - status
      - title
      - message
    error_too_many_requests:
      description: A response describing a rate limit error
      type: object
      properties:
        status:
          type: integer
          example: 429
        title:
          type: string
          example: Too Many Requests
        message:
          type: string
          example: Rate limit reached. Please wait for a couple of minutes.
      required:
      - status
      - title
      - message
    error_unprocessable_content:
      description: A response describing a validation error
      type: object
      properties:
        status:
          type: integer
          example: 422
        title:
          type: string
          example: Unprocessable Content
        message:
          type: string
          example: 'Validation failed: Title can''t be blank'
      required:
      - status
      - title
      - message
    error_unauthorized:
      description: A response describing an authentication error
      type: object
      properties:
        status:
          type: integer
          example: 401
        title:
          type: string
          example: Unauthorized
        message:
          type: string
          example: API token not found
      required:
      - status
      - title
      - message
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
x-readme:
  explorer-enabled: true
  proxy-enabled: true
